### ISSUE TITLE
Is it possible to buy pre-assembled and flashed?

### ISSUE THREAD

**Issue by kyvaith** [foorschtbar/LoRaProMini#3]

**Comment by kyvaith** [comment]
Or would it be possible to use something like this instead? https://www.tindie.com/products/iotmcu/lora-radio-node-v10/

**Comment by foorschtbar** [comment]
Please contact me via [Telegram](https://t.me/foorschtbar) or [Mastodon](https://chaos.social/@foorschtbar) direct message.
